name: CI - Pytest + Playwright

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      # ✅ Affichage virtuel pour faire tourner headless=False sans modifier ton code
      - name: Install Xvfb (virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run pytest under Xvfb
        run: |
          xvfb-run -a \
            pytest -q \
              --browser chromium \
              --tracing on

      - name: Upload artifacts (reports/traces)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results/**/*
            playwright-report/**/*
            **/screenshots/**
            **/videos/**
            **/*trace*.zip
          if-no-files-found: ignore
